name    'morphizer-sabnzbd'
version '0.1.0'
author 'morphizer'
license 'Apache License, Version 2.0'
summary 'SABnzbd news reader install and configure'
description 'SABnzbd is an Open Source Binary Newsreader written in Python. This module installs and configures it for use on Ubuntu/Debian based machines'
project_page 'http://github.com/morphizer/puppet-sabnzbd'
